name: SAM Validate
description: Assume one AWS role from another 
inputs:
  ROLE:
    description: "The role to assume"
    required: true

runs:
  using: "composite"
  
  steps:
    
    - name: sam validate
      run: |
        sam validate
      shell: bash