name: SAM 
description: SAM 
inputs:
  environment:
    description: Environment
    required: false
  action:
    description: Action
    required: true
    
runs:
  using: "composite"
  
  steps:

    - name: sam delete
      if: inputs.action == 'delete'
      run: |
        if [[ "${{inputs.environment}}" == "" ]]; then
          echo "::error environment parameter not supplied"
          exit 1
        fi
        sam delete --config-env ${{ inputs.environment }}  --config-file samconfig.yml --no-prompts
      shell: bash

    - name: sam deploy
      if: inputs.action == 'deploy'
      run: |
        if [[ "${{inputs.environment}}" == "" ]]; then
          echo "::error environment parameter not supplied"
          exit 1
        fi
        sam deploy --no-confirm-changeset --config-env ${{ inputs.environment }}  
      shell: bash

    - name: sam build
      if: inputs.action == 'build'
      run: |
        sam build
      shell: bash

    - name: sam validate
      if: inputs.action == 'validate'
      run: |
        sam validate
      shell: bash