version: 0.1
dev01: 
  global:
    parameters:
      s3_prefix: "lambda"
      region: eu-west-2
      stack_name: github-actions-with-aws-sam
  build:
    parameters:
      cached: true
      parallel: true
  validate:
    parameters:
      lint: true
  package:
    parameters:
      resolve_s3: false
  sync:
    parameters:
      watch: true
  local_start_api:
    parameters:
      warm_containers: EAGER
  local_start_lambda:
    parameters:
      warm_containers: EAGER
  deploy:
    parameters:
      s3_bucket: potteringabout-dev-remind
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      resolve_s3: false
      tags: foo=bar hello=world

