name: SAM Delete
description: SAM Delete
inputs:
  environment:
    description: Environment
    required: true
  
runs:
  using: "composite"
  
  steps:
    
    - name: sam delete
      run: |
        sam delete --config-env ${{ inputs.environment }}  --config-file samconfig.yml --no-prompts
      shell: bash