name: SAM Deploy
description: SAM Deploy
inputs:
  region:
    description: AWS Region
    required: true
  bucket:
    description: S3 Bucket
    required: true
  bucket_path:
    description: S3 Bucket Path
    required: true

runs:
  using: "composite"
  
  steps:
    
    - name: sam deploy
      run: |
        sam deploy --no-confirm-changeset --region ${{ inputs.region }} --s3-bucket ${{ inputs.bucket }} --s3-prefix ${{ inputs.bucket_path }}         
      shell: bash