name: SAM Deploy
description: SAM Deploy
inputs:
  environment:
    description: Environment
    required: true
  
runs:
  using: "composite"
  
  steps:
    
    - name: sam deploy
      run: |
        sam deploy --no-confirm-changeset --config-env TEXT        
      shell: bash