name: sam
on:
  workflow_dispatch:
    inputs:
      environment:
         type: environment
         description: Select the environment
  #push:
  #  branches:
  #    - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: '1.100.0'
      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.IDENTITY_ROLE }}
          role-duration-seconds: 1800
          role-session-name: "gh-sam"
      - name: assume role
        uses: ./.github/actions/assume-role
        with:
          ROLE: ${{ vars.TARGET_ROLE }}
      #- name: assume role
      #  run: |
      #    export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws sts assume-role --role-arn ${{ vars.TARGET_ROLE }} --role-session-name MySessionName --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text))
      #    echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
      #    echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
      #    echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV
      #    aws s3 ls
      # sam build 
      - run: |
          #sam build --use-container
          aws s3 ls


     