name: sam
on:
  workflow_dispatch:
    inputs:
      environment:
         type: environment
         description: Select the environment
  #push:
  #  branches:
  #    - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.IDENTITY_ROLE }}
          role-duration-seconds: 1800
          role-session-name: "gh-sam"
      # sam build 
      - run: |
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws sts assume-role --role-arn ${{ vars.TARGET_ROLE }} --role-session-name MySessionName --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text))
          aws s3 ls
      # sam build 
      - run: |
          #sam build --use-container
          aws s3 ls


     